version: "3.7"

x-envv: &env
  DATASOURCE_URL: ${DATASOURCE_URL}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  VK_APP_ID: ${VK_APP_ID}
  VK_SECRET_KEY: ${VK_SECRET_KEY}
  TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID}
  TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}

services:

  common-service:
    build: ../m3-common-service/
    environment: *env
    depends_on: [ kafka, postgresql ]

  users-service:
    build: ../m3-users-service/
    environment: *env
    depends_on: [ kafka, postgresql ]

  game-service:
    build: ../m3-game-service/
    ports:
      - 8081:8081
    environment: *env
    depends_on: [ kafka, postgresql ]

  node:
    image: node
    environment:
      PROFILE: ${PROFILE}
    working_dir: /m3-node.${PROFILE}/server
    volumes:
      - ../m3-node:/m3-node.${PROFILE}
    entrypoint: bash -c "npm install && node run.js"
    depends_on: [ kafka ]

  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
    volumes:
      - ../m3-node/public:/m3-node/public
      - ./nginx/${PROFILE}/conf.d:/etc/nginx/conf.d
      - ${NGINX_SSL_CERTIFICATE}
      - ${NGINX_SSL_CERTIFICATE_KEY}
    depends_on: [ node ]

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    volumes:
      - pgdata:/var/lib/postgresql/data

  kafka:
    image: bitnami/kafka
    restart: unless-stopped
    hostname: "kafka"
    ports:
      - "9092:9092"
    volumes: [ kafka_data:/bitnami ]
    environment:
      KAFKA_HEAP_OPTS: -Xmx1024m -Xmn1k -Xss256k
      KAFKA_PROCESS_ROLES: 'broker, controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_OFFSETS_TOPIC_NUM_PARTITIONS: 1

volumes:
  DB_data:
  kafka_data:
  pgdata: