version: "3.7"
services:

  java-app:
    image: amazoncorretto
    depends_on:
      - mysql
      - kafka
    networks:
      - tri-base-net
        # ipv4_address: 10.5.0.7
        # 
        # 
  tribase:
    image: node
    environment:
      - PROFILE=${PROFILE}
    working_dir: /var/www/tri-base.${PROFILE}/server
    volumes:
      - ../tri-base:/var/www/tri-base.${PROFILE}
    entrypoint: bash -c "npm install && node run.js"
    networks:
      - tri-base-net
        #        ipv4_address: 10.5.0.6
        #        aliases:
        #  - tribase
        #  - m3
    depends_on:
      - mysql
      - kafka

  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT_HTTP}:${NGINX_PORT_HTTP}
      - ${NGINX_PORT_HTTPS}:${NGINX_PORT_HTTPS}
    volumes:
      - ../tri-base/public:/var/www/tri-base.${PROFILE}/public
      - ./nginx/${PROFILE}/conf.d:/etc/nginx/conf.d
      - ./keys/self-signed:/var/keys/self-signed/
      - /etc/letsencrypt:/var/keys/letsencrypt
    networks:
      - tri-base-net
        #  ipv4_address: 10.5.0.5
    depends_on:
      - tribase

  mysql-client:
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_HOST=mysql
    volumes:
      - ./init.sh:/var/scripts/init.sh
      - ./dump.sql:/var/scripts/dump.sql
    command: /bin/bash /var/scripts/init.sh
    networks:
      - tri-base-net
        #        ipv4_address: 10.5.0.14
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    #      - MYSQL_DATABASE=tri_base{$PROFILE}
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
     -  tri-base-net
    #        ipv4_address: 10.5.0.4



  kafka:
    image: confluentinc/cp-kafka:latest
    # ports profile depends, disable it, because bridge
    #    ports:
    #  - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - tri-base-net
        #        ipv4_address: 11.5.0.3

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      # ports profile depends, disable it, because bridge
      #    ports:
      #- 22181:2181
    networks:
      - tri-base-net
        #        ipv4_address: 11.5.0.2

volumes:
  mysql-volume:

networks:
  tri-base-net:
    driver: bridge
    ipam:
      config:
        - subnet: 11.5.0.0/16
          gateway: 11.5.0.1
