version: "3.7"

services:

  java-app:
    build: ../m3-users-service/
    environment:
      DATASOURCE_URL: ${DATASOURCE_URL}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      VK_APP_ID: ${VK_APP_ID}
      VK_SECRET_KEY: ${VK_SECRET_KEY}
    entrypoint: bash -c "java -jar auth-0.0.1-SNAPSHOT.jar"
    depends_on:
      - kafka
      - mysql
  node:
    image: node
    environment:
      PROFILE: ${PROFILE}
    working_dir: /m3-node.${PROFILE}/server
    volumes:
      - ../m3-node:/m3-node.${PROFILE}
    entrypoint: bash -c "npm install && node run.js"
    depends_on: [ mysql-migrator ]

  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
    volumes:
      - ../m3-node/public:/m3-node/public
      - ./nginx/${PROFILE}/conf.d:/etc/nginx/conf.d
      - ${NGINX_SSL_CERTIFICATE}
      - ${NGINX_SSL_CERTIFICATE_KEY}
    depends_on: [ node ]

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: [ mysql_data:/var/lib/mysql ]

  kafka:
    image: bitnami/kafka
    restart: unless-stopped
    hostname: "kafka"
    ports:
      - "9092:9092"
    volumes: [ kafka_data:/bitnami ]
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    volumes: [ zookeeper_data:/bitnami ]
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  mysql-migrator:
    image: mysql:5.7
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: [ ./migrator:/migrator ]
    entrypoint: bash /migrator/run.sh
    depends_on: [ mysql ]

volumes:
  mysql_data:
  kafka_data:
  zookeeper_data:
