version: "3.7"

services:

  java-app:
    image: amazoncorretto
    volumes:
      - ../m3-users-service/build/libs/:/m3-service/
    working_dir: /m3-service/
    entrypoint: java -jar auth-0.0.1-SNAPSHOT.jar
    depends_on:
      - kafka

  node:
    image: node
    environment:
      PROFILE: ${PROFILE}
    working_dir: /m3-node.${PROFILE}/server
    volumes:
      - ../m3-node:/m3-node.${PROFILE}
    entrypoint: bash -c "npm install && node run.js"
    depends_on: [ mysql-migrator ]

  nginx:
    image: nginx
    ports:
      - ${NGINX_PORT_HTTP}:80
      - ${NGINX_PORT_HTTPS}:443
    volumes:
      - ../m3-node/public:/m3-node/public
      - ./nginx/${PROFILE}/conf.d:/etc/nginx/conf.d
      - ${NGINX_SSL_CERTIFICATE}
      - ${NGINX_SSL_CERTIFICATE_KEY}
    depends_on: [ node ]

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: [ /var/lib/mysql ]

  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    volumes:
          - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  mysql-migrator:
    image: mysql:5.7
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: [ ./migrator:/migrator ]
    entrypoint: bash /migrator/run.sh
    depends_on: [ mysql ]


