version: "3.7"

services:

  mysql-test:
      image: mysql:5.7
      ports:
        - "13306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${DB_TEST_USER}
        MYSQL_PASSWORD: ${DB_TEST_PASSWORD}
        MYSQL_DATABASE: ${DB_TEST_DATABASE}
      volumes: [ DB_test_data:/var/lib/mysql ]

volumes:
  DB_test_data: